### ISSUE TITLE
Phone number accepted but formatting not done

### ISSUE THREAD

**Issue by JulienNevo** [TuleSimon/xMaterialccp#13]
There is a problematic discrepancy on French phone number (maybe others):
- (+33) indicates "6 12 34 56 78" as a placeholder. But if typing "612345678", the formatting is not performed whereas the phone number is correct.
- On the contrary, typing "06 12 34 56 78" is well formatted, and the phone number is accepted, but this is inconsistent with the placeholder.

**Comment by TuleSimon** [comment]
@JulienNevo thanks for this, i would check and revert

**Comment by TuleSimon** [comment]
@JulienNevo issue fixed
